# Generated by Django 4.0.6 on 2022-07-16 20:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_otp_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('tag_code', models.CharField(max_length=225)),
                ('condition', models.CharField(max_length=225)),
                ('specifications', models.CharField(max_length=225)),
                ('link', models.CharField(max_length=225)),
                ('price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_profile', to='authentication.userprofile')),
            ],
        ),
    ]
