# Generated by Django 4.0.6 on 2022-07-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Available', 'Available'), ('Out of stock', 'Out Of Stock')], max_length=255),
        ),
    ]
